"""empty message

Revision ID: ca43c6475076
Revises: 
Create Date: 2024-12-01 12:40:10.939882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca43c6475076'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('hashed_pwd', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'subscriber', 'user', 'incognito', name='userrole'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID identifier'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Creation datetime'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Update datetime'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_users')),
    sa.UniqueConstraint('email', name=op.f('UQ_users_email')),
    sa.UniqueConstraint('login', name=op.f('UQ_users_login')),
    schema='fake_currency_prediction_service'
    )
    op.create_table('tokens',
    sa.Column('jti', sa.UUID(), nullable=False, comment='JWT identifier'),
    sa.Column('subject', sa.UUID(), nullable=False),
    sa.Column('user_agent', sa.String(length=100), nullable=False, comment='User device description'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Creation datetime'),
    sa.ForeignKeyConstraint(['subject'], ['fake_currency_prediction_service.users.id'], name=op.f('FK_tokens_subject_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti', name=op.f('PK_tokens')),
    schema='fake_currency_prediction_service'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens', schema='fake_currency_prediction_service')
    op.drop_table('users', schema='fake_currency_prediction_service')
    op.execute("DROP TYPE IF EXISTS userrole")
    # ### end Alembic commands ###
